# Global exports
export COLORTERM=truecolor
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LIBGL_ALWAYS_INDIRECT=1

# Check for updates
test -s ${HOME}/.dotfiles/update_online && /bin/bash ${HOME}/.dotfiles/update_online

# Load Antigen
test -s /usr/share/zsh-antigen/antigen.zsh && source /usr/share/zsh-antigen/antigen.zsh
test -s ${HOME}/.antigenrc && antigen init ${HOME}/.antigenrc
test -s ${HOME}/.p10k.zsh && source ${HOME}/.p10k.zsh
autoload -U compinit && compinit
unsetopt BEEP

# Additional variables
if [[ $(command -v nvim) != "" ]]; then
  test -x $(which nvim) && export EDITOR=$(which nvim)
fi

test -d ${HOME}/.npm_packages && export NPM_CONFIG_PREFIX="${HOME}/.npm_packages"

# Export aliases
if [[ $(command -v sudoedit) != "" ]]; then
  test -x $(which sudoedit) && alias svi="sudoedit "
fi

if [[ $(command -v microk8s) != "" ]]; then
  test -x $(which microk8s) && alias kubectl="microk8s kubectl "
fi

# Update PATH
test -d /usr/local/sbin && PATH=/usr/local/sbin:$PATH
test -d ${HOME}/.npm_packages && PATH=${HOME}/.npm_packages/bin:$PATH

# Cleanup
typeset -U PATH
export PATH

# Run local config
test -e ${HOME}/.zshrc.local && source ${HOME}/.zshrc.local
