# Global exports
export COLORTERM=truecolor
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8
export LIBGL_ALWAYS_INDIRECT=1
export ITERM2_SQUELCH_MARK=1

# Check for updates
test -e ${HOME}/.dotfiles/update_online && /bin/bash ${HOME}/.dotfiles/update_online

# Load Antigen
printf "\r\033[0;92m[  ..  ]\033[0m Session startup"
test -e /usr/share/zsh-antigen/antigen.zsh && source /usr/share/zsh-antigen/antigen.zsh
test -e ${HOME}/.antigenrc && antigen init ${HOME}/.antigenrc
test -e ${HOME}/.p10k.zsh && source ${HOME}/.p10k.zsh
autoload -U compinit && compinit
unsetopt BEEP

# Additional variables
test -e $(which nvim) && export EDITOR=$(which nvim)
test -e ${HOME}/.npm_packages && export NPM_CONFIG_PREFIX="${HOME}/.npm_packages"

# Export aliases
test -e $(which sudoedit) && alias svi="sudoedit "

# Update PATH
test -e ${HOME}/.npm_packages && PATH=${HOME}/.npm_packages/bin:$PATH
test -e /usr/local/sbin && PATH=/usr/local/sbin:$PATH

# Cleanup
typeset -U PATH
export PATH

# Run local config
test -e ${HOME}/.zshrc.local && source ${HOME}/.zshrc.local
printf "\r\033[0;92m[  OK  ]\033[0m Session startup\n"
